services:
  - type: web
    name: conversational-cfo
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python src/server.py
    plan: free
    autoDeploy: false
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: LAVA_FORWARD_TOKEN
        sync: false
      - key: LAVA_BASE_URL
        value: https://api.lavapayments.com/v1/forward
      - key: POKE_API_KEY
        sync: false
